/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_cameratest_GifUtil */

#ifndef _Included_com_example_cameratest_GifUtil
#define _Included_com_example_cameratest_GifUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_cameratest_GifUtil
 * Method:    Init
 * Signature: (Ljava/lang/String;IIIII)I
 */
JNIEXPORT jint JNICALL Java_com_example_cameratest_GifUtil_Init
  (JNIEnv *, jobject, jstring, jint, jint, jint, jint, jint);

/*
 * Class:     com_example_cameratest_GifUtil
 * Method:    Close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_cameratest_GifUtil_Close
  (JNIEnv *, jobject);

/*
 * Class:     com_example_cameratest_GifUtil
 * Method:    AddFrame
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_com_example_cameratest_GifUtil_AddFrame
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
